Di 23770 truncate collection UI
Pepperi-Addons/User-Defined-Collections pull request #184
Opened 2024-02-19 14:14 UTC by OdedAnswer

2024-02-19 16:16 UTC, roiaharon-pepperi requested changes

2024-02-19 16:16 UTC, roiaharon-pepperi commented on client-side/src/app/collection/collection-list.component.ts
> +                    actions.push({
this should only be visible is the collection is not of type 'contained'. like the "Edit Data" option

2024-02-20 10:43 UTC, roiaharon-pepperi requested changes

2024-02-20 10:43 UTC, roiaharon-pepperi commented on client-side/src/app/collection/collection-list.component.ts
> +                    if (selectedCollection && selectedCollection.Type != 'contained') {
there is literally the same if 1 line below.. please merge them

2024-02-20 10:50 UTC, OdedAnswer commented on client-side/src/app/collection/collection-list.component.ts
> +                    if (selectedCollection && selectedCollection.Type != 'contained') {
ah crap my brain is porridge

2024-02-20 10:57 UTC, roiaharon-pepperi approved these changes

2024-02-20 10:58 UTC, merged