Di 24015 add fields limitation validation
Pepperi-Addons/User-Defined-Collections pull request #187
Opened 2024-03-05 13:12 UTC by OdedAnswer

there are some commits that shouldn't be there (namely the permissions) because it seems I mistakenly branched out from the wrong branch, but it's a branch that was already merged, so should be fine

2024-03-06 10:25 UTC, roiaharon-pepperi requested changes

2024-03-06 15:03 UTC, OdedAnswer commented on client-side/src/app/collection/collection-list.component.ts
> +        this.utilitiesService.getFieldLimit().then((value: number) => sessionStorage.setItem('fieldsLimit', value.toString()));
when.. the session ends?

2024-03-07 17:12 UTC, roiaharon-pepperi requested changes

2024-03-07 17:12 UTC, roiaharon-pepperi commented on client-side/src/app/collection/form/tabs/general/general-tab.component.ts
> +        if (Object.keys(this.collection.Fields).length >= this.fieldsLimit) {
it's not that easy to check it.. if the collection have contained resource type field you should include the inner count inside.
this is the logic on the server side
for (const fieldID of Object.keys(collectionObj.Fields!)) {
                if (collectionObj.Fields![fieldID].Type === 'ContainedResource') { // if field type is contained, count contained schema fields
                    const collectionFieldsCount = await this.getCollectionFieldsLength(collectionObj.Fields![fieldID].Resource!);
                    fieldsCount += collectionFieldsCount;
                } else {
                    fieldsCount++;
                }

2024-03-07 17:12 UTC, roiaharon-pepperi commented on server-side/api.ts
> +            const fieldsLimit = await varRelationService.getSettingsByName(limitationTypes.Fields);
if the collection is of type 'contained' there is a different limit. you need to get a different key

2024-03-11 16:48 UTC, roiaharon-pepperi requested changes

2024-03-11 16:48 UTC, roiaharon-pepperi commented on client-side/src/app/collection/form/tabs/general/general-tab.component.ts
> +            if (this.getTotalFieldsCount(this.collection) > this.fieldsLimit) {
this check should be before you close the dialog. you can't delete the field, especially if it's "edit".

2024-03-20 13:42 UTC, roiaharon-pepperi approved these changes

2024-03-20 14:25 UTC, merged